version: "3.7"
services:
    my-box:
        build: .
        image: "${NAME}:${TAG}"
        restart: always
        stdin_open: true
        tty: true
        hostname: box
        container_name: box
        volumes:
            - "/opt/lb/tools:/opt/lb/tools"
            - "/opt/lb/.ssh:/root/.ssh"
