version: "3.7"
services:
    my-box:
        build: .
        image: "${NAME}:${TAG}"
        restart: always
        stdin_open: true
        tty: true
        hostname: box
        container_name: box
        environment:
          - KUBECONFIG=/opt/lb/tools/helm/config
        volumes:
            - "/opt/lb:/opt/lb"
            - "/opt/lb/.ssh:/root/.ssh"
            - "./resolv.conf:/etc/resolv.conf"
            - "~/.bash_aliases:/root/.bash_aliases"
        
