name: Build new image
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
      - .env

jobs:
  build:
    # Stage name
    name: build-img
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Step build
    steps:
    - uses: actions/checkout@v1
    - name: Build Img
      run: |
        echo "${{ secrets.MY_DOCKER_LOGIN }}" | docker login -u "alirom93" --password-stdin
        docker-compose build
        docker-compose push
    - name: Notify slack fail
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Docker Build Failed"
